### ISSUE TITLE
switch error?

### ISSUE THREAD

**Issue by tvckerwash** [Chocohead/Rift#12]
im trying to download the snapshot but every time i do i get this error message
![screenshot 673](https://user-images.githubusercontent.com/46145949/50430863-24f52500-088c-11e9-996a-ed7f229ee5f9.png)
i'm pretty sure i've done everything correctly so far and i know i have java fully installed so i have no idea why i'd get this error. thanks for the help in advance!

**Comment by gbl** [comment]
Seems like your open handler for .jar files got messed up somehow. Open a command line, cd to your desktop directory (where you downloaded the jar file to), and run java -jar Rift-jitpack-1b46b5dcf4-1.jar

**Comment by tvckerwash** [comment]
> Seems like your open handler for .jar files got messed up somehow. Open a command line, cd to your desktop directory (where you downloaded the jar file to), and run java -jar Rift-jitpack-1b46b5dcf4-1.jar

sorry for not answering i've been sick but that didn't work either. i've tried uninstalling and reinstalling java and installing a different version of java and none of those worked either. in the case of the different version of java it wouldn't even give me an error window it was like nothing happened.

**Comment by Chocohead** [comment]
Windows isn't pointing to the right Java executable, I'd suggest trying [Jarfix](https://johann.loefflmann.net/en/software/jarfix/index.html) to reset it to what it should be.

**Comment by tvckerwash** [comment]
> Windows isn't pointing to the right Java executable, I'd suggest trying [Jarfix](https://johann.loefflmann.net/en/software/jarfix/index.html) to reset it to what it should be.

that worked! thank you!
