### ISSUE TITLE
Rift 1.13.2 Server Crash with Aether Legacy Rift Mod

### ISSUE THREAD

**Issue by BenGeeLIVE** [Chocohead/Rift#14]
I tried making a server using the Rift Jar file. I am able to get the server started without using rift and then again with Rift without using the Aether Legacy Mod Rift 1.13.2. I start the server using Rift with the Aether mod installed the server crashes. Here is the server log. https://paste.ee/p/yYTFT

**Comment by Chocohead** [comment]
That looks like the 1.13 crash bug with Aether Legacy (that was fixed in Modding-Legacy/Aether-Legacy-Rift#15), potentially that wasn't merged into 1.13.2. Either way it is almost certainly an Aether rather than Rift bug.
