### ISSUE TITLE
Optifine + voxelmap  and xray

### ISSUE THREAD

**Issue by RaceF** [Chocohead/Rift#20]
When i try to join an server i get this message.

i am using:

optifine 1.13.2 e5
voxelmap 1.8.2 for 1.13.2
rift modlist 2.0.1b
x13-1.0.3

The game crashed whilst tesselating block model
The game crashed whilst tesselating block model
Error: java.lang.NoClassDefFoundError: net/optifine/util/BlockUtils

**Comment by Chocohead** [comment]
Issue with xray, BlockUtils#shouldSideBeRendered has apparently changed signature in newer Optifine versions which has broken the Mixin xray is making.
