### ISSUE TITLE
Crash with OptiFine on 1.13.2

### ISSUE THREAD

**Issue by kotauskas** [Chocohead/Rift#22]
Rift 1.13.2 with VoxelMap and OptiFine was working fine until today. It just stopped working, giving out this error: https://pastebin.com/B5LuR8az. The game window is successfully created and Mojang logo shown (though it hits 70% CPU activity), but then it closes, saying that it can't find net.optifine.CustomColors. Checked OptiFine JAR, totally fine (from optifine.net, latest version).

My specs:
Windows 10 64 bit October 2018 Update (1809)
Intel Core i5-2300 @ 2.8 GHz
PowerColor AMD Radeon 6770
Latest Minecraft launcher with embedded Java 8

**Comment by trgwii** [comment]
I got this exact same problem with the same versions today as well, on 2 computers. It was working fine until today, the setup hasn't changed. Looks like something has changed / been updated in the launcher that crashes this. Using OptiFine and VoxelMap. Removing OptiFine makes it run fine, using OptiFine without Rift also works.

Game version: 1.13.2
[Rift version](https://jitpack.io/com/github/Chocohead/Rift/jitpack-SNAPSHOT/Rift-jitpack-SNAPSHOT.jar) (Gets stored as Rift-jitpack-2cb118e6e0-1.jar)
OptiFine version: OptiFine 1.13.2 HD U E5
Java version:
```
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```
Windows version: 10.0.17134

**Comment by RaceF** [comment]
i also got the same issue.

**Comment by Sethenor** [comment]
same as in issue #21

**Comment by SAwings** [comment]
i also get same problem
net.optifine.CustomColors 
only OptiFine 1.13.2 have

**Comment by Baget86** [comment]
same issue

**Comment by mlk6450** [comment]
I don't want to feel like a broken record but, same. I am glad I found this thread because I am currently reinstalling everything because I thought my Minecraft had just gotten corrupted or something

**Comment by trgwii** [comment]
@Chocohead are there snapshot builds of the fixed version? No readme here :(

**Comment by trgwii** [comment]
Okay, this is interesting, today it magically works! Does Rift phone home at startup?

**Comment by Chocohead** [comment]
Rift doesn't do any networking client side. Running a Rift server will grab the vanilla server jar and dependencies if they're not present but that's only for running a server. The launcher you're using might however, turns out the vanilla launcher will automatically update over time if the URL to a dependency has changes. You can stop it doing this changing from the `SNAPSHOT` link to a static one if the profile json if you particularly wanted to.

**Comment by trgwii** [comment]
Ahh, thanks for the explanation and the great work on this project!
