### ISSUE TITLE
how to install it with launcher like HMCL？

### ISSUE THREAD

**Issue by SekiBetu** [Chocohead/Rift#25]
https://github.com/huanghongxun/HMCL

rift only install on the default .minecraft

how to install it on other root?

**Comment by Chocohead** [comment]
If you run the Rift jar with [`--install`](https://github.com/Chocohead/Rift/blob/jitpack/src/main/java/org/dimdev/riftloader/Main.java#L30) it will open a file picker dialog for you to choose where it gets installed to. It will still make the presumption that the folder structure is the same as .minecraft though
