### ISSUE TITLE
Can't compile since today

### ISSUE THREAD

**Issue by lordrius** [Chocohead/Rift#30]
Hi!

Since today, when i try to compile my mod, console throws an error:

> Could not resolve all files for configuration: ':implementation'

> Could not find com.github.Chocohead:Rift:jitpack-SNAPSHOT.

My dependencies code is the same as the example build.gradle.

`dependencies
{
	implementation 'com.github.Chocohead:Rift:jitpack-SNAPSHOT:dev'
}`

Any ideas?

Thanks.

**Comment by Chocohead** [comment]
Everything should work again now. Not sure what breaks it, but I know how to fix it at least.
