### ISSUE TITLE
spigot compat

### ISSUE THREAD

**Issue by Synthmania** [Chocohead/Rift#31]
hey will there be a spigot bridge or something for rift? It says Spigot support coming soon on the curse page of rift...

**Comment by Chocohead** [comment]
I'm not going to be adding it at this point, if someone else wants to I'll happily merge it in though.

**Comment by liach** [comment]
so is choco mostly dedicated on fabric now?

**Comment by Chocohead** [comment]
I've not added anything new to Rift since the start of February. It's not like there's been any new mods that have needed something they couldn't do themselves either. With 1.13(.2) is only going to wind down more 1.14 is proving a far more interesting (and longer term) investment of time.
