### ISSUE TITLE
Jitpack Download Broken (as of 27 April 2019)

### ISSUE THREAD

**Issue by DelKatey** [Chocohead/Rift#35]
It is not possible to get the [file](https://jitpack.io/com/github/Chocohead/Rift/jitpack-SNAPSHOT/Rift-jitpack-SNAPSHOT.jar) from the jitpack servers currently, it seems.

The page which is opened seems to be endlessly loading, and when an attempt to start up Minecraft is made, this message appears:

> Name: Rift-jitpack-SNAPSHOT.jar
URL: https://www.jitpack.io/com/github/Chocohead/Rift/jitpack-SNAPSHOT/Rift-jitpack-SNAPSHOT.jar
Filename on disk: Rift-jitpack-SNAPSHOT.jar
Path: C:\Users\user\AppData\Roaming\.minecraft\libraries\com\github\Chocohead\Rift\jitpack-SNAPSHOT\Rift-jitpack-SNAPSHOT.jar
Exists: false

**Comment by Maximilian213** [comment]
![error](https://user-images.githubusercontent.com/50047379/56849733-f43bff80-6900-11e9-83e9-37bbfa170430.png)
Look at this, same with me..

**Comment by SkullWolfSteam** [comment]
will this get fixed as me and a friend use the mod loader alot i legit fresh reinstalled my minecraft because it took so long to load then i saw the same error you guys got and was like wtf i hope this gets fixxed sometime soon.

**Comment by Maximilian213** [comment]
UPDATE: 

It works now for me folks, good luck!

**Comment by ghost** [comment]
It would appear everything is working as of few minutes ago.

**Comment by DelKatey** [comment]
I can also confirm that it's working now.

**Comment by MrMody0** [comment]
Hi, problem exists again, i can't download and if i got file from another source - launcher still can't run with this problem. What I have learned is the fact that the launcher is giving error: 
"Gave up trying to download https://www.jitpack.io/com/github/Chocohead/Rift/jitpack-SNAPSHOT/Rift-jitpack-SNAPSHOT.jar"
Link provides to site: 
"https://www.jitpack.io/com/github/Chocohead/Rift/jitpack-2d8bb9bd56-/Rift-jitpack-2d8bb9bd56-.jar"
Which is not working, but if you add "1" after "-" in two spots - just before ".jar", and earlier before the "/", it's downloading. Can you fix it please? :D

**Comment by Nezdera** [comment]
Doesn't work for me either...
I tried moving the download manually to the path the launcher gives but problem still persists.

**Comment by ItayZiv** [comment]
I managed to get it working by creating the exact path (.minecraft\libraries\com\github\Chocohead\Rift\jitpack-SNAPSHOT)
Then putting the jar in and renaming it to Rift-jitpack-SNAPSHOT.jar

**Comment by Nezdera** [comment]
Hmmm, I tried that exact thing but it didn't work. Guess I'll try again :p

It worked!

**Comment by surekqomi** [comment]
Seems the link has now changed from -1 to -11. After that the above workarounds are still effective.
