### ISSUE TITLE
[Feature Request] Forge

### ISSUE THREAD

**Issue by arturek1666** [Chocohead/Rift#38]
Can you add support for forge, as there is good amount of mods for rift but there are also good mods for forge It would be great if you can combine 2 of them. Example you putting rift mod to mods folder and on first run in .minecraft it will show riftmods folder where you can put rift mods there

**Comment by Chocohead** [comment]
There's no Mixin support for Forge right now so there's nothing that can be done. With 1.14 going so quickly as well I don't see 1.13.2 lasting long enough for it to ever happen. Can add it if it ever does though.
