### ISSUE TITLE
Minecraft won't open..

### ISSUE THREAD

**Issue by Maximilian213** [Chocohead/Rift#39]
Normal day, just want to play some minecraft and then, all the sudden my launcher is stuck at preparing with 0 MB, please fix your rift pack.

**Comment by surekqomi** [comment]
Same issue as happened in #35 and #37.

**Comment by Chocohead** [comment]
Should be fully fixed via d4cd7b00baf9a699356fb7aed036bd0d426cbf30, might take a single re-run of the installer if it happens again in future.
