### ISSUE TITLE
Rift 1.13.2 Game crashes, no solution

### ISSUE THREAD

**Issue by OddBlueberry** [Chocohead/Rift#47]
ERROR Game crashed An unexpected issue has occurred and the game has crashed. We're sorry for the inconvenience.
I'm on Windows 10, x64. This error message is all I'm getting when I try to run Minecraft with just Rift alone, the plan was to have Optifine and Voxelmap as well but I've just given up trying to solve it on my own as this is the most trouble I've ever had with a mod.

The following has been done:
Looked through the open and closed issues on Github, following #37 and #42
Searching for a helpful Youtube video
Clean install of Rift, Minecraft, Java
Restarting PC after those were uninstalled

And still the simple game error, yes I've looked at my log and they would look the same, just a name difference inside if I changed a file name/string trying to follow the above. Thank you!

**Comment by forkiesassds** [comment]
It seems like the original developer's maven repo is down, and it requires it to download a library which is needed for mixin's
