### ISSUE TITLE
Default water texture with Sildur's Shaders

### ISSUE THREAD

**Issue by ScottoMotto** [Chocohead/Rift#5]
Sildur's Shaders has been updated for 1.13.2 and it works fine with Optifine 1.13.2 Ultra E4 when installed alone.

https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1291396-1-6-4-1-13-2-sildurs-shaders-pc-mac-intel-vibrant

![optfine only water](https://user-images.githubusercontent.com/40503051/49663165-67f17480-fa13-11e8-84aa-e44c4e12a7b0.png)

With the Rift loader all seems to work but the water.

![rift optifine no water](https://user-images.githubusercontent.com/40503051/49663202-89526080-fa13-11e8-86ba-7ed8bd5c5de8.png)

**Comment by Chocohead** [comment]
This is closely related to #1, although not the same cause.

**Comment by ScottoMotto** [comment]
Thanks it is fixed.
