### ISSUE TITLE
Couldn't find class "ayu" during injection

### ISSUE THREAD

**Issue by tatanpoker09** [Chocohead/Rift#6]
I was trying to use the version under the Play in Minecraft 1.13.2, but it didn't work under the problem "Couldn't Inject registerBiomes, blah blah, class "ayu" was not found." I just fixed it by installing version: https://jitpack.io/com/github/Chocohead/Rift/jitpack-c767d08919-1/
If you want, I can try to reinstall the other version and send a stacktrace, but it was just during the Injection in https://github.com/DimensionalDevelopment/Rift/blob/master/src/main/java/org/dimdev/rift/mixin/hook/MixinBiome.java
Thanks!

**Comment by Chocohead** [comment]
Oops, looks like I put a `remap = false` in the wrong set of brackets.

**Comment by jessiewestlake** [comment]
How do we use the fixed version? Do I have to build from src? Cause I have this same problem still.

**Comment by Chocohead** [comment]
It should be available from the normal [download](https://jitpack.io/com/github/Chocohead/Rift/jitpack-SNAPSHOT/Rift-jitpack-SNAPSHOT.jar) now as `Rift-jitpack-25f930e39e-1.jar`.

**Comment by jessiewestlake** [comment]
I'm not great with GitHub, how would I have found that download file myself? I usually only find builds under "Releases" which latest is from Sept 9.

**Comment by Chocohead** [comment]
How everything is setup at the moment isn't really using Github, what's there is the 1.13 stuff which I haven't touched (hence it's from early September). It will be once we've got the versioning sorted out though.

Right now everything is built periodically (automatically every day) which is where the normal download link goes. I can force it to rebuilt immediately though which is how we didn't have to wait a day for this fix to come out.
You can tell when it has last been built from the part at the end of the versioning, the `25f930e39e` part is the start of the commit identifier which every change to the repo has. You can see them [here](https://github.com/Chocohead/Rift/commits/jitpack) in red:
![demonstration image](https://user-images.githubusercontent.com/4021725/49691579-df232780-fb3d-11e8-9380-b5c6050cf0e1.PNG)
I've underlined the merge which fixed this issue (in blue), which you can see starts with `25f930e` and if you click on it the URL provides the entire identifier (`25f930e39e0d6ba6d73b246c48cb18cb479e42c4`) which is much longer. The daily build's version is the first 10 characters of this long identifier.

If you wanted a particular branch yourself, say to compare something or if the normal download hasn't updated yet, `https://jitpack.io/com/github/Chocohead/Rift/<entire identifier>` will build the commit you pick and show you what it made if it succeeds.
`https://jitpack.io/com/github/Chocohead/Rift/25f930e39e0d6ba6d73b246c48cb18cb479e42c4/` for example gives us a list including `Rift-25f930e39e0d6ba6d73b246c48cb18cb479e42c4.jar`. If you put that at the end of the URL (ie `https://jitpack.io/com/github/Chocohead/Rift/25f930e39e0d6ba6d73b246c48cb18cb479e42c4/Rift-25f930e39e0d6ba6d73b246c48cb18cb479e42c4.jar`), you can download it. This is the same jar as `Rift-jitpack-25f930e39e-1.jar`, the difference is the first is asking for it directly, and the second is the daily build.

I try my best to ensure the daily build is updated immediately for changes when possible, especially for crash fixes. Hopefully this makes the process a little more clear, especially for whether the daily build has actually changed or not.

**Comment by tatanpoker09** [comment]
Thanks for your hard work man<3
