### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [Chocohead/Rift#8]

**Comment by Chocohead** [comment]
Did you add Optifine to the mods folder or as a jar mod/tweaker?

**Comment by Eddi2015** [comment]
Ok, so I played a bit around with it and it looks like they both don't like each other. OptiFine alone = ok and also Rift alone = ok, but together this crash happens. And yes I'm using Optifine as a tweaker (as written on MultiMC's wiki).

**Comment by Eddi2015** [comment]
Ok, so I just followed the installation video posted in this issue: https://github.com/Chocohead/Rift/issues/7

And now everything works. I made the whole thing more complicated than what it actually is. I didn't know Rift can load OptiFine from the mods folder.
