### ISSUE TITLE
Minecraft 1.13.2 crashes

### ISSUE THREAD

**Issue by ScaroMX** [Chocohead/Rift#9]
It loads but just before it show the main game screen it crashes and gives me this error:
Error: java.lang.VerifyError: Instruction type does not match stack map

Thanks

**Comment by Chocohead** [comment]
Presuming this is the same as DimensionalDevelopment/Rift#70

What mods are you trying to use? This is very likely from using a 1.13 mod on 1.13.2

**Comment by ScaroMX** [comment]
I had several mods from diferent versions. I tried just with voxel minimap and optifine for version 1.13.2 both and it worked!!!!, minecraft launched just right and rift loaded these mods.
Thank you.

**Comment by Chocohead** [comment]
Good to hear you got it working
